### ISSUE TITLE
Isn't idempotent; doesn't recognize if new rules have manually been added to iptables.

### ISSUE THREAD

**Issue by jtviolet** [chef-cookbooks/iptables#58]
### Cookbook version

2.2.0
### Chef-client version

12.5
### Platform Details

CentOS 6.7
### Scenario:

I have a set list of firewall rules that Chef manages. If a rogue users goes in and manually adds a new rule to /etc/sysconfig/iptables, chef-client won't correct it during the next run of iptables.
### Steps to Reproduce:

Set a list of firewall rules in chef, and run chef-client. Manually add a firewall rule to /etc/sysconfig/iptables, then restart/reload the service. Run chef-client again. Your manually added firewall rule will still be there.
### Expected Result:

After running, the iptables resource should be able to detect a difference in it's output of iptables versus the current iptables in place, and change only if there is a difference.
### Actual Result:

It notices no difference, and will not change anything even if a new rule has been manually added.

**Comment by martinb3** [comment]
Generally, this cookbook doesn't support modifying the state of the firewall outside of Chef. We would have to start parsing firewall rule syntax across three different implementations, just to identify manually added rules, OR we'd have to clear the entire rule tables on every chef run. We also would break support for things like fail2ban if we began removing its rules on every run.

We used to have this cookbook parse the running state of the firewall, and it was fraught with peril -- constant bugs and problems. This cookbook _will_ fix the firewall if you edit the files on disk that contain rules, but that's because Chef gives us an easy implementation for detecting when files don't match. We simply don't have a nice implementation across ufw, iptables, and firewalld, to parse rules manually.

**Comment by jperville** [comment]
I just got bitten by this: after `yum update iptables`, the content of `/etc/sysconfig/iptables` has been replaced with a default version; the original contents (generated by this cookbook) has been moved to .rpmsave extension.

At the next chef-run, the cookbook will not notice that iptables rules have been altered, does not rebuild the /etc/sysconfig/iptables file and does not reload the rules.

**Comment by bby-bishopclark** [comment]
change 
https://github.com/chef-cookbooks/iptables/blob/master/recipes/default.rb#L53
to just :create ?

It should invoke the diff check and copy the proper (tiny) version into place, right?

**Comment by jblaine** [comment]
Not sure how this is a "Feature Request" instead of a bug :). The persisted file can be tampered with (maliciously or otherwise by yum for instance) out of band thereby subverting the entire firewall policy defined in Chef until the next `rebuild-iptables` run is triggered by _rule changes_ (could be an hour from now, could be months from now).

Maybe have `rebuild-iptables` write out a checksum of the persisted file it wrote out, then check the checksums (every chef run) in the default recipe and force a run of `rebuild-iptables` if they differ?

**Comment by Xorima** [comment]
Hi,

I am closing this as it relates to an old version of the cookbook which has since been fundamentally changed. If you still have the issue with the latest version please could you open a new issue,

Thanks
